from fastmcp import FastMCP

mcp = FastMCP(name="SandboxMCPServer")


@mcp.tool
async def echo(message: str) -> str:
    """Echo back the provided message"""
    return f"Echo: {message}"


@mcp.tool
async def add_numbers(a: int, b: int) -> int:
    """Add two numbers together"""
    return a + b


@mcp.tool
async def multiply_numbers(a: int, b: int) -> int:
    """Multiply two numbers together"""
    return a * b


@mcp.tool
async def get_server_info() -> dict:
    """Get information about this MCP server"""
    return {
        "name": "TestMCPServer",
        "version": "1.0.0",
        "description": "A test MCP server for CarbonScope",
        "tools": ["echo", "add_numbers", "multiply_numbers", "get_server_info"],
    }


@mcp.tool
async def read_generated_file(filepath: str) -> str:
    """Read a file generated by the autonomous dev agent in the workspace."""
    import os
    base_dir = "/workspace"
    target_path = os.path.abspath(os.path.join(base_dir, filepath))
    
    if not target_path.startswith(base_dir):
        return "Error: Access denied. Cannot read outside workspace."
        
    try:
        with open(target_path, "r") as f:
            return f.read()
    except Exception as e:
        return f"Error reading file: {e}"

@mcp.tool
async def list_generated_files(directory: str = ".") -> list:
    """List all files in a workspace directory."""
    import os
    base_dir = "/workspace"
    target_path = os.path.abspath(os.path.join(base_dir, directory))
    
    if not target_path.startswith(base_dir):
        return ["Error: Access denied. Cannot read outside workspace."]
        
    try:
        return os.listdir(target_path)
    except Exception as e:
        return [f"Error listing directory: {e}"]

@mcp.resource("greeting://{name}")
async def get_greeting(name: str) -> str:
    """Get a personalized greeting"""
    return f"Hello, {name}! Welcome to the Dev Sandbox MCP Server."


if __name__ == "__main__":
    mcp.run(transport="streamable-http", host="0.0.0.0", port=8002)
